package java_.problem.problem_0002;

public class Problem {

	public static final String DESCRIPTION = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\r\n"
			+ "\t  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\r\n"
			+ "\t  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";

	public static int solve() {

		int solution = 0;

		int a = 1;
		int b = 2;

		while (b < 4000000) {

			solution += b % 2 == 0 ? b : 0;

			int new_number = a + b;
			a = b;
			b = new_number;

		}

		return solution;

	}

}

//int a = 1;
//int b = 1;
//int c = 2;
//
//while (c < 4000000) {
//	solution += c;
//	a = b + c;
//	b = c + a;
//	c = a + b;
//}