package java_.problem.problem_0029;

import java.math.BigInteger;
import java.util.HashSet;

public class Problem {

	public static final String DESCRIPTION = "Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:\r\n\r\n"
			+ "\t  22=4,  23=8,   24=16,  25=32\r\n" + "\t  32=9,  33=27,  34=81,  35=243\r\n"
			+ "\t  42=16, 43=64,  44=256, 45=1024\r\n" + "\t  52=25, 53=125, 54=625, 55=3125\r\n\r\n"
			+ "\t  If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:\r\n"
			+ "\t  4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125\r\n"
			+ "\t  How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?";

	public static int solve() {

		HashSet<BigInteger> sorted = new HashSet<BigInteger>();

		for (int a = 2; a <= 100; a++) {
			BigInteger number = BigInteger.valueOf(a);
			for (int b = 2; b <= 100; b++) {
				number = number.multiply(BigInteger.valueOf(a));
				sorted.add(number);
			}
		}

		return sorted.size();
	}

}