package java_.problem.problem_0044;

public class Problem {

	public static final String DESCRIPTION = "Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:\r\n"
			+ "\t\t  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...\r\n"
			+ "\t  It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.\r\n"
			+ "\t  Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?";

	public static long solve() {
		long result = Integer.MAX_VALUE;
		int i = 1;

		while (true) {
			i++;
			long n = i * (3l * i - 1) / 2;

			for (int j = i - 1; j > 0; j--) {
				long m = j * (3l * j - 1) / 2;

				if (n - m > result)
					break;

				if (isPentagonal(n - m) && isPentagonal(n + m)) {
					if (n - m < result) {
						result = n - m;
						break;
					}
				}
			}

			if (n - (i - 1) * (3l * (i - 1) - 1) / 2 > result)
				break;
		}

		return result;
	}

	private static boolean isPentagonal(long pNumber) {
		return (Math.sqrt(1 + 24 * pNumber) + 1) % 6 == 0;
	}

}
